{"name": "test_login_failed[data2]", "status": "passed", "attachments": [{"name": "log", "source": "6c890700-17cd-4737-a4ac-fc0e38804c70-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录-反向用例-密码为空', 'username': 'caiyou', 'password': '', 'error_msg': '账号登录'}"}], "start": 1614175918258, "stop": 1614175921879, "uuid": "833e6189-61a2-47bd-a443-17b8392a32a3", "historyId": "daee70692129a544e4ece7a1edb1fbca", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "15232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}