{"name": "test_login_failed[data2]", "status": "passed", "attachments": [{"name": "log", "source": "463e61f8-4695-4554-8ae8-f751bcaa188e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录-反向用例-密码为空', 'username': 'caiyou', 'password': '', 'error_msg': '账号登录'}"}], "start": 1614176064012, "stop": 1614176067619, "uuid": "f7190090-21f1-47b5-bd6a-438e7fac890f", "historyId": "daee70692129a544e4ece7a1edb1fbca", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "2540-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}