{"name": "test_login_failed[data3]", "status": "passed", "attachments": [{"name": "log", "source": "c33fb4b0-ad80-4771-946b-9b18b5886cf7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录-反向用例-密码错误', 'username': '财友2sna6763', 'password': '123456', 'error_msg': '账号或密码错误'}"}], "start": 1614175536218, "stop": 1614175539901, "uuid": "9b1b6c53-0dcd-46ba-b2cc-e7f4f216cb9e", "historyId": "dbeb2a97f887c27b8015e9253b5aa614", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ruslan"}, {"name": "thread", "value": "3064-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}